### ISSUE TITLE
restyle website

### ISSUE THREAD

**Issue by andrew21-mch** [skye8-tech/skye8.tech#17]

**Comment by andrew21-mch** [comment]
@Tita-Tera @mulfranck 
work on restyling the website, some merging conflicted the styles

**Comment by mulfranck** [comment]
@andrew21-mch, Sorry took so long.
- I have fix all broken links 
There was a problem displaying content, it seems the php tags on the first line was not working probably.

**Comment by andrew21-mch** [comment]
thanks, have you managed to fix it ? @mulfranck

**Comment by andrew21-mch** [comment]
thanks @mulfranck , I will be close this issue, 
if you notice, i wrote a simple .htaccess file, this tries to remove .php extensions for all files when you type them on the browser
the next task will be for you you to go through the headers, remove .php extensions in all the links 
exampe `<a href="services.php">Services </a>` becomes `<a href="services">Services </a>` 

do you understand ?

**Comment by mulfranck** [comment]
Okay, I never understood the .htaccess file was file 🤣

**Comment by mulfranck** [comment]
> thanks, have you managed to fix it ? @mulfranck

Nope, it just commented the lines and did my part and un-commented the guy back.

**Comment by andrew21-mch** [comment]
> > thanks, have you managed to fix it ? @mulfranck
> 
> Nope, it just commented the lines and did my part and un-commented the guy back.

please which pages, so i can fix it

**Comment by mulfranck** [comment]
The main _index.php_ page for the home

I don't know, maybe its my setup

**Comment by andrew21-mch** [comment]
wait
are you running on xampp

**Comment by andrew21-mch** [comment]
the index page works here

**Comment by mulfranck** [comment]
> wait are you running on xampp

Nope, using apache2

**Comment by andrew21-mch** [comment]
> > wait are you running on xampp
> 
> Nope, using apache2

please if you have xampp try to use it,
