### ISSUE TITLE
Help with my local php setup

### ISSUE THREAD

**Issue by mulfranck** [skye8-tech/skye8.tech#22]
I started the repo with xampp as you suggested 
![Screenshot from 2022-12-25 19-26-31](https://user-images.githubusercontent.com/74215941/209478733-3707f357-beaa-4bb6-a3da-78035a68050f.png)

and I got this error then.
how am i to get the database?

**Comment by andrew21-mch** [comment]
okay let me see what to do here

**Comment by andrew21-mch** [comment]
[skye8tech.zip](https://github.com/skye8-tech/skye8.tech/files/10300569/skye8tech.zip)

unzip this file, it contains the sql to run to setup your database

steps

- [ ] unzip
- [ ] upon xampp
- [ ] create a database called `skye8tech`
- [ ] click on the database created, 
- [ ] look to the tope nav you will see a place called `import`
- [ ] click on it, then select the file to extracted to import
- [ ] thats it, your database should be setup, 
- [ ] before you run, make sure xampp is started, you should also know that password of your xampp (by default its empty string) except you changed it when installing

**Comment by mulfranck** [comment]
Thanks, all did work well.

**Comment by andrew21-mch** [comment]
great, 

> Thanks, all did work well.

great
